import { MarketSnapshot } from "@/types/market";

/** Minimal snapshot for unit tests — fill only fields under test. */
export function makeSnapshot(
  overrides: Partial<MarketSnapshot> = {}
): MarketSnapshot {
  return {
    fetchedAt: "2026-06-01T00:00:00.000Z",
    identifiers: {
      city: "Austin",
      state: "Texas",
      stateAbbr: "TX",
      metroArea: "Austin-Round Rock",
      fipsCode: "12420",
      cbsaCode: "12420",
      zipCodes: ["78701"],
      latitude: 30.27,
      longitude: -97.74,
      ...overrides.identifiers,
    },
    gdpCurrent: null,
    gdp1yr: null,
    gdp5yr: null,
    gdp10yr: null,
    gdpGrowth: null,
    population: null,
    medianIncome: null,
    medianHomePrice: null,
    rentalPopulationPct: null,
    netMigrationPct: null,
    unemploymentRate: null,
    jobGrowthPct: null,
    annualRentalIncome: null,
    medianRent: null,
    housingAffordabilityIndex: null,
    priceToRentRatio: null,
    monthsOfInventory: null,
    daysOnMarket: null,
    medianListPrice: null,
    strAdr: null,
    strOccupancyRate: null,
    strRevpar: null,
    strAnnualRevenue: null,
    strMonthlyRevenue: null,
    strActiveListings: null,
    strSeasonalityScore: null,
    strOccupancyD30: null,
    strOccupancyD60: null,
    strOccupancyD90: null,
    strOccupancyD365: null,
    strAvgRating: null,
    strMedianReviews: null,
    strSuperhostPct: null,
    strMedianBedrooms: null,
    strTypicalMinNights: null,
    strBookedNights: null,
    strAvailableNights: null,
    strAdrP25: null,
    strAdrP75: null,
    strSegment2brAdr: null,
    strSegment2brOccupancy: null,
    strSegment2brRevpar: null,
    strSegment2brCount: null,
    strListingPins: [],
    strFetchError: null,
    strLoadComplete: null,
    crimeRateViolent: null,
    crimeRateProperty: null,
    keyIndustries: null,
    majorEmployers: null,
    landlordFriendly: null,
    stateTaxRate: null,
    propertyTaxRate: null,
    strRegulationScore: null,
    strRegulationSignals: null,
    strRegulationNotes: null,
    strRegulationSources: null,
    strRegulationVerifiedAt: null,
    strRegulationConfidence: null,
    strRegulationJurisdiction: null,
    strInvestorEligible: null,
    strRegulationResolution: null,
    walkScore: null,
    transitScore: null,
    bikeScore: null,
    overallScore: null,
    overallRating: null,
    ...overrides,
  };
}
